development:
  adapter: postgresql
  encoding: unicode
  database: dart_score_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: dart_score_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: dart_score_production
  pool: 5
  timeout: 5000
